##### WORKING MAIN #####
# EXCEL_FILE = 'G:\\!TEST\\data.xlsx'
# UPLOAD_FOLDER  = 'G:\\!TEST\\uploads'
# PROXY_FOLDER = 'G:\\!TEST\\proxy'
# BACKREMOVE_DELETED_PATH = 'G:\\!PORTRETY_DATABASE\\DELETED'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


##### FOR TEST #####
EXCEL_FILE = '!TEST/data.xlsx'
UPLOAD_FOLDER  = '!TEST'
PROXY_FOLDER = '!TEST/AVATARS'
BACKREMOVE_DELETED_PATH = '!TEST/DELETED'